begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values
('e0900000-0000-4000-8000-000000000001','sender@email.test',now(),'{"full_name":"Responsável"}'),
('e0900000-0000-4000-8000-000000000002','member@email.test',now(),'{"full_name":"Membro"}'),
('e0900000-0000-4000-8000-000000000003','other@email.test',now(),'{"full_name":"Outra pessoa"}');
create temp table email_ids(company uuid, invitation uuid, job uuid);
grant all on email_ids to authenticated, service_role;
select set_config('request.jwt.claim.sub','e0900000-0000-4000-8000-000000000001',true);
set local role authenticated;
insert into email_ids(company) select (public.create_company('Empresa do e-mail')).id;
update email_ids set invitation=(public.invite_collaborator(company,'invited@email.test')).id;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'42501',null,'Browser cannot reserve mail jobs');
select throws_ok($$select public.finish_invitation_email(gen_random_uuid(),'fake')$$,'42501',null,'Browser cannot confirm email delivery');
select throws_ok($$update public.workspace_invitations set email_status='sent'$$,'42501',null,'Browser cannot forge a sent state');
select throws_ok($$select * from private.invitation_email_jobs$$,'42501',null,'Mail snapshots are private');
reset role;
insert into public.workspace_members(workspace_id,user_id,role) select company,'e0900000-0000-4000-8000-000000000002','member' from email_ids;
set local role service_role;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000002','https://orbit.test','access@orbit.test')$$,'42501',null,'Member cannot trigger email');
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000003','https://orbit.test','access@orbit.test')$$,'42501',null,'Other company cannot trigger email');
update email_ids set job=(public.prepare_invitation_email(invitation,'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')->>'id')::uuid;
select is((select email_status from public.workspace_invitations where id=(select invitation from email_ids)),'sending','Reserve persists sending state');
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'PT429',null,'Duplicate sends are rate limited');
select is(public.finish_invitation_email((select job from email_ids)),(select invitation from email_ids),'Failed attempt confirms affected invitation');
select is((select email_status from public.workspace_invitations where id=(select invitation from email_ids)),'failed','Provider failure is persisted');
reset role;
select is((select reply_to from private.invitation_email_jobs where id=(select job from email_ids)),'sender@email.test','Reply-To comes from Auth');
update public.workspace_invitations set email_requested_at=now()-interval '2 minutes' where id=(select invitation from email_ids);
update public.profiles set full_name='Nome alterado' where id='e0900000-0000-4000-8000-000000000001';
set local role service_role;
select is((public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://changed.test','other@orbit.test')->>'id')::uuid,(select job from email_ids),'Retry keeps provider idempotency key');
reset role;
select is((select inviter_name from private.invitation_email_jobs where id=(select job from email_ids)),'Responsável','Retry preserves immutable message name');
select ok((select invitation_url from private.invitation_email_jobs where id=(select job from email_ids)) like 'https://orbit.test/%','Retry preserves application link');
set local role service_role;
select throws_ok($$select public.finish_invitation_email((select job from email_ids),' ')$$,'22023',null,'Empty provider identifier cannot confirm success');
select is(public.finish_invitation_email((select job from email_ids),'resend-message-1'),(select invitation from email_ids),'Success confirms invitation');
select is((select email_status from public.workspace_invitations where id=(select invitation from email_ids)),'sent','Sent status is persisted');
select ok((select email_sent_at is not null from public.workspace_invitations where id=(select invitation from email_ids)),'Sent timestamp exists');
select public.finish_invitation_email((select job from email_ids));
select is((select email_status from public.workspace_invitations where id=(select invitation from email_ids)),'sent','Delayed failure cannot undo a successful send');
reset role;
update public.workspace_invitations set email_requested_at=now()-interval '2 minutes' where id=(select invitation from email_ids);
set local role service_role;
select isnt((public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')->>'id')::uuid,(select job from email_ids),'Explicit resend creates a new delivery after cooldown');
reset role;
update public.workspace_invitations set status='revoked' where id=(select invitation from email_ids);
set local role service_role;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'PT410',null,'Revoked invitation is not emailed');
reset role;
update public.workspace_invitations set status='pending',expires_at=now()-interval '1 second' where id=(select invitation from email_ids);
set local role service_role;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'PT410',null,'Expired invitation is not emailed');
reset role;
update auth.users set email_confirmed_at=null where id='e0900000-0000-4000-8000-000000000001';
set local role service_role;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'42501',null,'Even an administrator must have a confirmed email');
reset role;
update auth.users set email_confirmed_at=now() where id='e0900000-0000-4000-8000-000000000001';
update public.workspace_invitations set expires_at=now()+interval '7 days',email_requested_at=now()-interval '2 minutes',email_job_id=null where id=(select invitation from email_ids);
insert into private.invitation_email_jobs(invitation_id,workspace_id,requested_by,recipient,inviter_name,reply_to,company_name,sender_email,invitation_url,expires_at)
select j.invitation_id,j.workspace_id,j.requested_by,j.recipient,j.inviter_name,j.reply_to,j.company_name,j.sender_email,j.invitation_url,j.expires_at
from private.invitation_email_jobs j cross join generate_series(1,30) where j.id=(select job from email_ids);
set local role service_role;
select throws_ok($$select public.prepare_invitation_email((select invitation from email_ids),'e0900000-0000-4000-8000-000000000001','https://orbit.test','access@orbit.test')$$,'PT429',null,'Company hourly limit is enforced in the database');
reset role;
select * from finish();
rollback;
