import { expect, test } from '@playwright/test'

for (const kind of ['project', 'task']) {
  test(`datepicker shadcn no formulário de ${kind}: teclado, mês/ano e envio`, async ({ page }, testInfo) => {
    await page.clock.setFixedTime(new Date(2026, 9, 8, 12))
    await page.goto(`/tests/fixtures/date-picker.html?kind=${kind}`)
    await page.getByLabel(kind === 'project' ? 'Nome do projeto' : 'Nome da tarefa').fill('Verificar prazo')
    const trigger = page.getByLabel('Data de entrega', { exact: true })
    const popup = page.getByRole('dialog', { name: 'Selecionar data', exact: true })
    await trigger.focus()
    await page.keyboard.press('Enter')
    await expect(popup).toBeVisible()
    await expect(page.getByRole('button', { name: /^quinta-feira, 8 de outubro de 2026, hoje$/ })).toBeFocused()
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Enter')
    await expect(popup).not.toBeVisible()
    await expect(trigger).toHaveText('09/10/2026')
    await expect(trigger).toBeFocused()
    await expect(page.getByLabel('Data enviada')).toHaveCount(0)

    await trigger.click()
    await page.getByRole('combobox', { name: 'Ano', exact: true }).click()
    await expect(page.getByRole('listbox')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('listbox')).not.toBeVisible()
    await expect(popup).toBeVisible()
    await expect(page.getByRole('dialog', { name: 'Teste do formulário' })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Ano', exact: true })).toBeFocused()
    await page.keyboard.press('Enter')
    await page.getByRole('option', { name: '2028', exact: true }).click()
    await page.getByRole('combobox', { name: 'Mês', exact: true }).click()
    await page.getByRole('option', { name: /^fevereiro$/i }).click()
    await page.getByRole('button', { name: /^terça-feira, 29 de fevereiro de 2028$/ }).click()
    await expect(trigger).toHaveText('29/02/2028')
    await trigger.click()
    await expect(page.getByRole('button', { name: /29 de fevereiro de 2028, selecionado/ })).toBeFocused()
    await expect(popup).toBeInViewport({ ratio: 1 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    await page.screenshot({ path: testInfo.outputPath('calendar.png') })
    await page.keyboard.press('Escape')
    await expect(popup).not.toBeVisible()
    await expect(page.getByRole('dialog', { name: 'Teste do formulário' })).toBeVisible()
    await page.getByRole('button', { name: kind === 'project' ? 'Criar projeto' : 'Criar tarefa', exact: true }).click()
    await expect(page.getByLabel('Data enviada')).toHaveText('2028-02-29')

    await trigger.click()
    await page.getByRole('button', { name: 'Limpar data' }).click()
    await page.getByRole('button', { name: kind === 'project' ? 'Criar projeto' : 'Criar tarefa', exact: true }).click()
    await expect(page.getByLabel('Data enviada')).toHaveText('Sem data')
  })
}
